### ISSUE TITLE
Support stable & nightly releases

### ISSUE THREAD

**Issue by richin13** [richin13/asdf-neovim#1]
`stable` and `nightly` releases are not supported yet

**Comment by pappasam** [comment]
I think this is broken because you're hard-coding this line: https://github.com/richin13/asdf-neovim/blob/master/bin/utils.sh#L19 with a v. It creates the URL https://github.com/neovim/neovim/releases/download/vnightly/nvim-linux64.tar.gz for nightly, which is "v"ery wrong :p

**Comment by zachliu** [comment]
i want the nightly so much, i want to program at night :crescent_moon:
