### ISSUE TITLE
macos arch releases

### ISSUE THREAD

**Issue by so-jelly** [richin13/asdf-neovim#23]
newovim releases are arch specific on macos in v0.10.0

attempting to download https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-macos.tar.gz and failing

**Comment by sneako** [comment]
This was fixed already in https://github.com/richin13/asdf-neovim/commit/cefa92a9ddeb5610b92813db2a68129fb2506f14

If you update the plugin it will work.

**Comment by richin13** [comment]
@so-jelly thanks! As @sneako stated above this was reported in #21 and it's been fixed. If you run:

```
asdf plugin update neovim
```

or if you use mise 

```
mise plugins update neovim
```

Then it should work appropriately. I'll close it for now but if there's anything else feel free to ping me!
